### ISSUE TITLE
Inconsistent markdown output for Detection Rules

### ISSUE THREAD

**Issue by herrBez** [krakow2600/atomic-threat-coverage#136]
The format of the output of markdown files (in particular the value of line "Trigger" in the table) is not always consistent. For instance, in the table of `./Atomic_Threat_Coverage/Detection_Rules/av_password_dumper.md`  we have an html list:
```html
<ul>
    <li>
          [T1003: Credential Dumping](../Triggers/T1003.md)
    </li>
</ul>
```

, while in file `./Atomic_Threat_Coverage/Detection_Rules/av_relevant_files.md` we have a simple text:
```
There is no Trigger for this technique yet.
```

I Would suggest to return an empty html list in the second case:
```html
<ul></ul>
```

So that the format is uniform.

The approach described here (return an empty HTML list), is taken for other lines of the tables as well (e.g., `ATT&amp;CK Technique ATT&amp;CK Tactic` in `./Atomic_Threat_Coverage/Detection_Rules/win_susp_userinit_child.md` or "References" in `./Atomic_Threat_Coverage/Detection_Rules/win_webshell_spawn.md`)

**Comment by yugoslavskiy** [comment]
Hello @herrBez ! Thank you for your proposal. Yesterday I've pushed [updates](https://github.com/krakow2600/atomic-threat-coverage/commit/f278b6e4a01040d520c0086d21ed8967a5d79853) on that to develop branch, but with a different approach. Now we will have messages regarding absence of some analytic:

- This Detection Rule wasn't mapped to ATT&amp;CK Tactic yet
- This Detection Rule wasn't mapped to ATT&amp;CK Technique yet
- There is no documented Data Needed for this Detection Rule yet
- There is no documented Trigger for this Detection Rule yet
- Data for this Detection Rule doesn't require any Enrichments. (markdown only, due to lack of ability to get rid of if not breaking the table)
- Severity Level for this Detection Rule wasn't defined yet
- There are no documented False Positives for this Detection Rule yet
- Development Status wasn't defined for this Detection Rule yet
- There are no documented References for this Detection Rule yet
- Author of this Detection Rule haven't introduced himself

It will fix inconsistency, but as I said, in a different way. We believe that empty field looks like something is broken on our side, and it's better to put there some explanation, than just left it empty.

**Comment by herrBez** [comment]
As long as it is documented, I'm fine :). Thank you for your work. I will close the issue.
